spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: backend-api
          uri: lb://BACKEND-API
          predicates:
            - Path=/backend/**
          filters:
#            - name: CircuitBreaker
#              args:
#                name: backend-api
#                fallbackuri: forward:/orderFallBack
        - id: web-api
          uri: lb://WEB-API
          predicates:
            - Path=/web/**
          filters:
#            - name: CircuitBreaker
#              args:
#                name: web-api
#                fallbackuri: forward:/paymentFallback


server:
  port: 8989