server:
  port: 9192
spring:
  data:
    rest:
      base-path: /backend
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  application:
    name: backend-api
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
